config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    patch :toggle_done, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update toggle_done destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all.order :created_at
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.turbo_stream
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('new_task',
             partial: 'form', locals: { task: @task })
        end
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@task)}
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /tasks/1/toggle_done or /tasks/1/toggle_done.json
  def toggle_done
    @task.toggle! :done
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
      format.turbo_stream { render turbo_stream: turbo_stream.replace(@task)}
      format.json { render :show, status: :ok, location: @task }
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@task)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:done, :title)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for task, wrapper: :inline_form, html: { class: "row #{'border-top' if task.persisted?} mt-2 pt-2" }, wrapper_mappings: { boolean: :inline_boolean } do |f|
  
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .col-sm-1
  .col-sm-11= f.input :title, label: false, placeholder: 'Add a New task here ...', input_html: { class: 'form-control-sm', autofocus: true }

app/views/tasks/_task.html.haml
= turbo_frame_tag task do
  .row.border-top.mt-2.pt-2
    .col-1      
      = link_to toggle_done_task_path(task), data: { turbo_method: 'patch' }, title: 'Toggle', class: 'text-decoration-none link-dark' do 
        = tag.i class: "bi bi#{'-check' if task.done}-square"
    = link_to edit_task_path(task), title: 'Edit', class: "col-10 text-decoration-none #{'text-decoration-line-through' if task.done} link-dark" do 
      = task.title
    .col-1    
      = link_to task, data: { turbo_method: :delete }, title: 'Destroy' do
        %i.bi.bi-trash.fs-5

app/views/tasks/create.turbo_stream.haml
= turbo_stream.append 'tasks', @task
= turbo_stream.replace 'new_task' do 
  = render 'form', task: Task.new

app/views/tasks/edit.html.haml
%h1 Editing task
= turbo_frame_tag @task do
  = render 'form', task: @task

= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Todo List 

.container#tasks
  = render 'form', task: Task.new
  = render @tasks
  

app/views/tasks/new.html.haml
%h1 New task

= render 'form', task: Task.new

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Done:
  = @task.done
%p
  %b Title:
  = @task.title

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path